### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Eszet**
Successful test with RME DAC in class-compliant mode.

### CODE REVIEW

**Comment by vincentneo** [comment]
Thanks for the addition!

**Comment by git-hub-pat** [comment]
It works on a M2 Mac mini with the IKKO ITM01s DAC. But sometimes when Apple Music is in the background it switches during a song to a complete different bitrate, or sampling rate...

**Comment by vincentneo** [comment]
Hi @git-hub-pat,
May I ask which version(s) was it that had the issue?

**Comment by git-hub-pat** [comment]
Here an example
￼

**Pull request merged**
